### ISSUE TITLE
Tracking Issue: Unit 6

### ISSUE THREAD

**Issue by DoubleF3lix** [DoubleF3lix/Java-Data-Pack-Tutorial#10]
- [ ] Lesson 1: Introduction to Scoreboards
- [ ] Lesson 2: Scoreboard Criteria
- [ ] Lesson 3: Assigning and Displaying Values
- [ ] Lesson 4: Doing Math with Operators
- [ ] Lesson 5: Fake Players
- [ ] Project 1: Calculator
- [ ] Lesson 6: Triggers
- [ ] Project 2: Non-Operator Functions

Please comment on this issue if it needs updating.
