### ISSUE TITLE
Tracking Issue: Unit 7

### ISSUE THREAD

**Issue by DoubleF3lix** [DoubleF3lix/Java-Data-Pack-Tutorial#11]
- [ ] Lesson 1: Introduction to NBT
    - [ ] Lesson 1.1: Structure
    - [ ] Lesson 1.2: Types
- [ ] Lesson 2: The Data Command
    - [ ] Lesson 2.1: Getting data
    - [ ] Lesson 2.2: Removing Data
    - [ ] Lesson 2.3: Modifying Data
- [ ] Lesson 3: Storing Data
- [ ] Lesson 4: Attributes
    - [ ] Lesson 4.1: Getting Attribute Values
    - [ ] Lesson 4.2: Setting Base Attribute Values
    - [ ] Lesson 4.3: Modifiers

Please comment on this issue if it needs updating.
