### ISSUE TITLE
Tracking Issue: Unit 12

### ISSUE THREAD

**Issue by DoubleF3lix** [DoubleF3lix/Java-Data-Pack-Tutorial#16]
- [ ] Project 1: Item Counter
- [ ] Lesson 1: Item Modifiers
- [ ] Lesson 2: Advanced Item Manipulation
- [ ] Project 2: Light Level Indicator

Please comment on this issue if it needs updating.
