### ISSUE TITLE
Tracking Issue: Unit 13

### ISSUE THREAD

**Issue by DoubleF3lix** [DoubleF3lix/Java-Data-Pack-Tutorial#17]
- [ ] Lesson 1: Pools
- [ ] Lesson 2: Functions (Item Modifiers)
- [ ] Lesson 3: Loot Command
- [ ] Project 1: Loot Crates
- [ ] Project 2: Biome Detector

Please comment on this issue if it needs updating.
