### ISSUE TITLE
Tracking Issue: Unit 14

### ISSUE THREAD

**Issue by DoubleF3lix** [DoubleF3lix/Java-Data-Pack-Tutorial#18]
- [ ] Lesson 1: Conditions with Predicates
- [ ] Lesson 2: Loot Table Conditions
- [ ] Lesson 3: Predicate Checking

Please comment on this issue if it needs updating.
