### ISSUE TITLE
Tracking Issue: Unit 1

### ISSUE THREAD

**Issue by DoubleF3lix** [DoubleF3lix/Java-Data-Pack-Tutorial#5]
- [ ] Lesson 1: Your First Data Pack
- [ ] Lesson 2: Your First Function
- [ ] Lesson 3: Ticks
- [ ] Lesson 4: Functions with Delays
- [ ] Project 1: Conversations

Please comment on this issue if it needs updating.
