### ISSUE TITLE
Tracking Issue: Unit 2

### ISSUE THREAD

**Issue by DoubleF3lix** [DoubleF3lix/Java-Data-Pack-Tutorial#6]
- [ ] Lesson 1: Introduction to Coordinates
- [ ] Lesson 2: Chunks
- [ ] Lesson 3: Block Manipulation
- [ ] Project 1: Building a Beacon
- [ ] Lesson 4: Spawnpoints
- [ ] Lesson 5: Locating

Please comment on this issue if it needs updating.
