### ISSUE TITLE
Tracking Issue: Unit 3

### ISSUE THREAD

**Issue by DoubleF3lix** [DoubleF3lix/Java-Data-Pack-Tutorial#7]
- [ ] Lesson 1: Formatting Text
- [ ] Lesson 2: Displaying Text
    - [ ] Lesson 2.1: Chat
    - [ ] Lesson 2.2: Titles
- [ ] Project 1: Prettier Conversations

Please comment on this issue if it needs updating.
