### ISSUE TITLE
Tracking Issue: Unit 4

### ISSUE THREAD

**Issue by DoubleF3lix** [DoubleF3lix/Java-Data-Pack-Tutorial#8]
- [ ] Lesson 1: Selectors
- [ ] Lesson 2: Summoning Entities
- [ ] Lesson 3: Entity Manipulation
- [ ] Project 1: Vanishing Pigs
- [ ] Lesson 4: Tagging Entities
- [ ] Lesson 5: Teams
    - [ ] Lesson 5.1: Introduction to Teams
    - [ ] Lesson 5.2: Team Rules
